// generation.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: generation.proto

package generation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationService_CreateGeneration_FullMethodName = "/generation.generationService/CreateGeneration"
)

// GenerationServiceClient is the client API for GenerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenerationServiceClient interface {
	CreateGeneration(ctx context.Context, in *CreateGenerationRequest, opts ...grpc.CallOption) (*CreateGenerationResponse, error)
}

type generationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationServiceClient(cc grpc.ClientConnInterface) GenerationServiceClient {
	return &generationServiceClient{cc}
}

func (c *generationServiceClient) CreateGeneration(ctx context.Context, in *CreateGenerationRequest, opts ...grpc.CallOption) (*CreateGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGenerationResponse)
	err := c.cc.Invoke(ctx, GenerationService_CreateGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerationServiceServer is the server API for GenerationService service.
// All implementations must embed UnimplementedGenerationServiceServer
// for forward compatibility.
type GenerationServiceServer interface {
	CreateGeneration(context.Context, *CreateGenerationRequest) (*CreateGenerationResponse, error)
	mustEmbedUnimplementedGenerationServiceServer()
}

// UnimplementedGenerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationServiceServer struct{}

func (UnimplementedGenerationServiceServer) CreateGeneration(context.Context, *CreateGenerationRequest) (*CreateGenerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGeneration not implemented")
}
func (UnimplementedGenerationServiceServer) mustEmbedUnimplementedGenerationServiceServer() {}
func (UnimplementedGenerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeGenerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationServiceServer will
// result in compilation errors.
type UnsafeGenerationServiceServer interface {
	mustEmbedUnimplementedGenerationServiceServer()
}

func RegisterGenerationServiceServer(s grpc.ServiceRegistrar, srv GenerationServiceServer) {
	// If the following call pancis, it indicates UnimplementedGenerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationService_ServiceDesc, srv)
}

func _GenerationService_CreateGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationServiceServer).CreateGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationService_CreateGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationServiceServer).CreateGeneration(ctx, req.(*CreateGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerationService_ServiceDesc is the grpc.ServiceDesc for GenerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generation.generationService",
	HandlerType: (*GenerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGeneration",
			Handler:    _GenerationService_CreateGeneration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generation.proto",
}
