# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/document_job.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/document_job.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/document_job.proto\x12\x0c\x64ocument_job\"K\n\x15\x44ocumentProcessingJob\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x11\n\tmodule_id\x18\x02 \x01(\x04\x12\x0e\n\x06\x64oc_id\x18\x03 \x01(\x04\x42\'Z%%replace%/internal/proto/document_jobb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.document_job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%%replace%/internal/proto/document_job'
  _globals['_DOCUMENTPROCESSINGJOB']._serialized_start=43
  _globals['_DOCUMENTPROCESSINGJOB']._serialized_end=118
# @@protoc_insertion_point(module_scope)
