version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "user_db"
      RESET_DB: "true"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis-auth
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mysql_data:
    driver: local

networks:
  backend:
    driver: bridge
