version: '3.8'

services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "user_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
      - ./database/auth_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mysql-memory:
    image: mysql:8.0
    container_name: mysql-memory
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "memory_db"
    ports:
      - "3307:3306"
    volumes:
      - mysql_memory_data:/var/lib/mysql
      - ./database/memory_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis-auth:
    image: redis:7.0
    container_name: redis-auth
    ports:
      - "6379:6379"
    networks:
      - backend
  redis-memory:
    image: redis:7.0
    container_name: redis-memory
    ports:
      - "6380:6379"
    networks:
      - backend

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: '20'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    ports:
      - "9000:8080"
      - "9001:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - backend

  # go-bff:
  #   build:
  #     context: ./backend/bff
  #   container_name: go-bff
  #   environment:
  #     CORS_ALLOWED_ORIGINS: "http://localhost:5173"
  #     BFF_SERVICE_HOST: "localhost"
  #     BFF_SERVICE_PORT: "8000"
  #     AUTH_SERVICE_HOST: "go-auth"
  #     AUTH_SERVICE_PORT: "50051"
  #   ports:
  #     - "8000:8000"  # Expose port 50051
  #   networks:
  #     - backend
  #   depends_on:
  #     - mysql-auth
  #     - mysql-memory
  #     - redis-auth
  #     - redis-memory
  # go-auth:
  #   build:
  #     context: ./backend/authentication_service
  #   container_name: go-auth
  #   environment:
  #     DB_USERNAME: "root"
  #     DB_PASSWORD: "password"
  #     DB_HOST: "mysql-auth"
  #     DB_PORT: "3306"
  #     DB_NAME: "user_db"
  #     DB_MAX_OPEN_CONNS: "10"
  #     DB_MAX_IDLE_CONNS: "10"
  #     DB_MAX_CONN_LIFETIME_MIN: "30m"
  #     REDIS_HOST: "redis-auth"
  #     REDIS_PORT: "6379"
  #   ports:
  #     - "50051:50051"  # Expose port 50051
  #   networks:
  #     - backend
  #   depends_on:
  #     mysql-auth:
  #       condition: service_healthy
  #     redis-auth:
  #       condition: service_started


volumes:
  mysql_auth_data:
    driver: local
  mysql_memory_data:
    driver: local
  weaviate_data:
    driver: local

networks:
  backend:
    driver: bridge
