# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protos import document_pb2 as protos_dot_document__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDoc = channel.unary_unary(
                '/document.DocService/CreateDoc',
                request_serializer=protos_dot_document__pb2.CreateDocRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.CreateDocResponse.FromString,
                _registered_method=True)
        self.GetDocById = channel.unary_unary(
                '/document.DocService/GetDocById',
                request_serializer=protos_dot_document__pb2.GetDocByIdRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.GetDocByIdResponse.FromString,
                _registered_method=True)
        self.GetDocsByModuleId = channel.unary_unary(
                '/document.DocService/GetDocsByModuleId',
                request_serializer=protos_dot_document__pb2.GetDocsByModuleIdRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.GetDocsByModuleIdResponse.FromString,
                _registered_method=True)
        self.GetDocsByNameSearch = channel.unary_unary(
                '/document.DocService/GetDocsByNameSearch',
                request_serializer=protos_dot_document__pb2.GetDocsByNameSearchRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.GetDocsByNameSearchResponse.FromString,
                _registered_method=True)
        self.UpdateDoc = channel.unary_unary(
                '/document.DocService/UpdateDoc',
                request_serializer=protos_dot_document__pb2.UpdateDocRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.UpdateDocResponse.FromString,
                _registered_method=True)
        self.DeleteDoc = channel.unary_unary(
                '/document.DocService/DeleteDoc',
                request_serializer=protos_dot_document__pb2.DeleteDocRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.DeleteDocResponse.FromString,
                _registered_method=True)
        self.UpdateSummary = channel.unary_unary(
                '/document.DocService/UpdateSummary',
                request_serializer=protos_dot_document__pb2.UpdateSummaryRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.UpdateSummaryResponse.FromString,
                _registered_method=True)
        self.UpdateUploadStatus = channel.unary_unary(
                '/document.DocService/UpdateUploadStatus',
                request_serializer=protos_dot_document__pb2.UpdateUploadStatusRequest.SerializeToString,
                response_deserializer=protos_dot_document__pb2.UpdateUploadStatusResponse.FromString,
                _registered_method=True)


class DocServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocsByModuleId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocsByNameSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUploadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDoc': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDoc,
                    request_deserializer=protos_dot_document__pb2.CreateDocRequest.FromString,
                    response_serializer=protos_dot_document__pb2.CreateDocResponse.SerializeToString,
            ),
            'GetDocById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocById,
                    request_deserializer=protos_dot_document__pb2.GetDocByIdRequest.FromString,
                    response_serializer=protos_dot_document__pb2.GetDocByIdResponse.SerializeToString,
            ),
            'GetDocsByModuleId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocsByModuleId,
                    request_deserializer=protos_dot_document__pb2.GetDocsByModuleIdRequest.FromString,
                    response_serializer=protos_dot_document__pb2.GetDocsByModuleIdResponse.SerializeToString,
            ),
            'GetDocsByNameSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocsByNameSearch,
                    request_deserializer=protos_dot_document__pb2.GetDocsByNameSearchRequest.FromString,
                    response_serializer=protos_dot_document__pb2.GetDocsByNameSearchResponse.SerializeToString,
            ),
            'UpdateDoc': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDoc,
                    request_deserializer=protos_dot_document__pb2.UpdateDocRequest.FromString,
                    response_serializer=protos_dot_document__pb2.UpdateDocResponse.SerializeToString,
            ),
            'DeleteDoc': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDoc,
                    request_deserializer=protos_dot_document__pb2.DeleteDocRequest.FromString,
                    response_serializer=protos_dot_document__pb2.DeleteDocResponse.SerializeToString,
            ),
            'UpdateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSummary,
                    request_deserializer=protos_dot_document__pb2.UpdateSummaryRequest.FromString,
                    response_serializer=protos_dot_document__pb2.UpdateSummaryResponse.SerializeToString,
            ),
            'UpdateUploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUploadStatus,
                    request_deserializer=protos_dot_document__pb2.UpdateUploadStatusRequest.FromString,
                    response_serializer=protos_dot_document__pb2.UpdateUploadStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/CreateDoc',
            protos_dot_document__pb2.CreateDocRequest.SerializeToString,
            protos_dot_document__pb2.CreateDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/GetDocById',
            protos_dot_document__pb2.GetDocByIdRequest.SerializeToString,
            protos_dot_document__pb2.GetDocByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocsByModuleId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/GetDocsByModuleId',
            protos_dot_document__pb2.GetDocsByModuleIdRequest.SerializeToString,
            protos_dot_document__pb2.GetDocsByModuleIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocsByNameSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/GetDocsByNameSearch',
            protos_dot_document__pb2.GetDocsByNameSearchRequest.SerializeToString,
            protos_dot_document__pb2.GetDocsByNameSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/UpdateDoc',
            protos_dot_document__pb2.UpdateDocRequest.SerializeToString,
            protos_dot_document__pb2.UpdateDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/DeleteDoc',
            protos_dot_document__pb2.DeleteDocRequest.SerializeToString,
            protos_dot_document__pb2.DeleteDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/UpdateSummary',
            protos_dot_document__pb2.UpdateSummaryRequest.SerializeToString,
            protos_dot_document__pb2.UpdateSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocService/UpdateUploadStatus',
            protos_dot_document__pb2.UpdateUploadStatusRequest.SerializeToString,
            protos_dot_document__pb2.UpdateUploadStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
