# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/generation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protos import common_pb2 as protos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/generation.proto\x12\ngeneration\x1a\x13protos/common.proto\"\x86\x01\n\x17\x43reateGenerationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x1f\n\x07id_type\x18\x03 \x01(\x0e\x32\x0e.common.IDType\x12-\n\x0c\x63hat_history\x18\x04 \x03(\x0b\x32\x17.generation.ChatHistory\",\n\x18\x43reateGenerationResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"K\n\x0b\x43hatHistory\x12+\n\x0b\x65ntity_type\x18\x01 \x01(\x0e\x32\x16.generation.EntityType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t*l\n\nEntityType\x12\x1b\n\x17\x45NTITY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x45NTITY_TYPE_SYSTEM\x10\x01\x12\x14\n\x10\x45NTITY_TYPE_USER\x10\x02\x12\x13\n\x0f\x45NTITY_TYPE_BOT\x10\x03\x32r\n\x11generationService\x12]\n\x10\x43reateGeneration\x12#.generation.CreateGenerationRequest\x1a$.generation.CreateGenerationResponseB%Z#%replace%/internal/proto/generationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#%replace%/internal/proto/generation'
  _globals['_ENTITYTYPE']._serialized_start=320
  _globals['_ENTITYTYPE']._serialized_end=428
  _globals['_CREATEGENERATIONREQUEST']._serialized_start=61
  _globals['_CREATEGENERATIONREQUEST']._serialized_end=195
  _globals['_CREATEGENERATIONRESPONSE']._serialized_start=197
  _globals['_CREATEGENERATIONRESPONSE']._serialized_end=241
  _globals['_CHATHISTORY']._serialized_start=243
  _globals['_CHATHISTORY']._serialized_end=318
  _globals['_GENERATIONSERVICE']._serialized_start=430
  _globals['_GENERATIONSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
