# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/vector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protos import common_pb2 as protos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/vector.proto\x12\x06vector\x1a\x13protos/common.proto\"o\n\x19\x43reateMemoryVectorRequest\x12\x11\n\tmodule_id\x18\x01 \x01(\x04\x12\x11\n\tmemory_id\x18\x02 \x01(\x04\x12\x14\n\x0cmemory_title\x18\x03 \x01(\t\x12\x16\n\x0ememory_content\x18\x04 \x01(\t\"\x1c\n\x1a\x43reateMemoryVectorResponse\"m\n\x19SearchMemoryVectorRequest\x12\x14\n\x0csearch_query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x04\x12\n\n\x02id\x18\x03 \x01(\x04\x12\x1f\n\x07id_type\x18\x04 \x01(\x0e\x32\x0e.common.IDType\"3\n\x1aSearchMemoryVectorResponse\x12\x15\n\rjson_response\x18\x01 \x01(\x0c\x32\xc9\x01\n\rVectorService\x12[\n\x12\x43reateMemoryVector\x12!.vector.CreateMemoryVectorRequest\x1a\".vector.CreateMemoryVectorResponse\x12[\n\x12SearchMemoryVector\x12!.vector.SearchMemoryVectorRequest\x1a\".vector.SearchMemoryVectorResponseB!Z\x1f%replace%/internal/proto/vectorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037%replace%/internal/proto/vector'
  _globals['_CREATEMEMORYVECTORREQUEST']._serialized_start=52
  _globals['_CREATEMEMORYVECTORREQUEST']._serialized_end=163
  _globals['_CREATEMEMORYVECTORRESPONSE']._serialized_start=165
  _globals['_CREATEMEMORYVECTORRESPONSE']._serialized_end=193
  _globals['_SEARCHMEMORYVECTORREQUEST']._serialized_start=195
  _globals['_SEARCHMEMORYVECTORREQUEST']._serialized_end=304
  _globals['_SEARCHMEMORYVECTORRESPONSE']._serialized_start=306
  _globals['_SEARCHMEMORYVECTORRESPONSE']._serialized_end=357
  _globals['_VECTORSERVICE']._serialized_start=360
  _globals['_VECTORSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
