// vector.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: vector.proto

package vector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorService_CreateMemoryVector_FullMethodName = "/vector.VectorService/CreateMemoryVector"
	VectorService_SearchMemoryVector_FullMethodName = "/vector.VectorService/SearchMemoryVector"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	CreateMemoryVector(ctx context.Context, in *CreateMemoryVectorRequest, opts ...grpc.CallOption) (*CreateMemoryVectorResponse, error)
	SearchMemoryVector(ctx context.Context, in *SearchMemoryVectorRequest, opts ...grpc.CallOption) (*SearchMemoryVectorResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) CreateMemoryVector(ctx context.Context, in *CreateMemoryVectorRequest, opts ...grpc.CallOption) (*CreateMemoryVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMemoryVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_CreateMemoryVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) SearchMemoryVector(ctx context.Context, in *SearchMemoryVectorRequest, opts ...grpc.CallOption) (*SearchMemoryVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMemoryVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_SearchMemoryVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility.
type VectorServiceServer interface {
	CreateMemoryVector(context.Context, *CreateMemoryVectorRequest) (*CreateMemoryVectorResponse, error)
	SearchMemoryVector(context.Context, *SearchMemoryVectorRequest) (*SearchMemoryVectorResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorServiceServer struct{}

func (UnimplementedVectorServiceServer) CreateMemoryVector(context.Context, *CreateMemoryVectorRequest) (*CreateMemoryVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMemoryVector not implemented")
}
func (UnimplementedVectorServiceServer) SearchMemoryVector(context.Context, *SearchMemoryVectorRequest) (*SearchMemoryVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMemoryVector not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}
func (UnimplementedVectorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_CreateMemoryVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).CreateMemoryVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_CreateMemoryVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).CreateMemoryVector(ctx, req.(*CreateMemoryVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_SearchMemoryVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoryVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).SearchMemoryVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_SearchMemoryVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).SearchMemoryVector(ctx, req.(*SearchMemoryVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vector.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMemoryVector",
			Handler:    _VectorService_CreateMemoryVector_Handler,
		},
		{
			MethodName: "SearchMemoryVector",
			Handler:    _VectorService_SearchMemoryVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vector.proto",
}
